### ISSUE TITLE
it can't pack android arm64-v8a so file

### ISSUE THREAD

**Issue by pcheng74** [upx/upx#100]
## What's the problem (or question)?

It can't pack the android arm64-v8a so file
## What should have happened?

it will return InternalError: unknown relocation type 'R_AARCH64_CALL26'

## Do you have an idea for a solution?

No
## How can we reproduce the issue?

1. Use android studio 2.3 to create a simple project.
2. During project creation, there is a option "include C++ support", just select it.

3. Edit build.gradle as below to build arm64-v8a
 externalNativeBuild {
            cmake {
                cppFlags "-frtti"
                abiFilters  'arm64-v8a'// 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'arm64-v8a', 'mips', 'mips64'
            }
        }
4. Edit native-lib.cpp file as below.
--------------------------------------------------------------------------------------------------
#include <jni.h>
#include <string>
#include <android/log.h>

#define  LOG_TAG "LOG_HELLO"
#define  LOGI(...)  __android_log_print(ANDROID_LOG_INFO,LOG_TAG,__VA_ARGS__)
#define  LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG,__VA_ARGS__)

extern "C" void _init(void){
    LOGI("native-lib _init log test ok");
}

extern "C"
JNIEXPORT jstring JNICALL
Java_com_bitanswer_bitnativedemo_MainActivity_stringFromJNI(
        JNIEnv* env,
        jobject /* this */) {
    std::string hello = "Hello from C++";

    LOGI("Hello from C");
    return env->NewStringUTF(hello.c_str());
}

extern "C" jint JNICALL JNI_OnLoad(JavaVM * vm, void* reserved)
{
    JNIEnv* env = NULL;
    jint result = -1;

    if (vm->GetEnv((void**) &env, JNI_VERSION_1_4) != JNI_OK) {
        LOGI("native-lib  JNI_OnLoad failed, env != JNI_VERSION_1_4");
        return -1;
    }

    /* success -- return valid version number */
    result = JNI_VERSION_1_4;
    LOGI("native-lib JNI_OnLoad log test ok");
    return result;
}
-------------------------------------------------------------------------------------------------
## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.94
* Host Operating System and version: Windows 10
* Host CPU architecture:
* Target Operating System and version: Android 
* Target CPU architecture: ARM 64

**Comment by jreiser** [comment]
Please attach the (zipped) .so file to this Issue; that should be at most a couple kilobytes.  [See "Attach files by ..." at the bottom of a Write pane for this Issue.]  Android Studio 2.3 is not "turn key": installing it omits [apparently necessary] pieces that must be tracked down; that is not nice.

**Comment by pcheng74** [comment]
[libnative-lib.zip](https://github.com/upx/upx/files/1018558/libnative-lib.zip)

**Comment by pcheng74** [comment]
Yes,  Android studio 2.3 is not a key factor, in fact I tried eclipse with ADT also.
Please see above attached file.

**Comment by jreiser** [comment]
Fixed by commit f42a37555d9a2f5df78f808daf192ce6615b4d17 on 'devel' branch.  Also, you might want to use the upx command-line parameter "--android-shlib" in order to pacify the linker on Android N.

**Comment by pcheng74** [comment]
Hi jreiser,

I tried the latest code with --android-shilib command-line parameter. However it still has the following error during execution:
05-29 08:30:11.960 3243-3243/com.hfm.demo5 E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.hfm.demo5, PID: 3243
                                                             java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.hfm.demo5-2/lib/arm64/libtest.so" has invalid offset/size of .dynamic section
                                                                 at java.lang.Runtime.loadLibrary0(Runtime.java:977)
                                                                 at java.lang.System.loadLibrary(System.java:1530)
                                                                 at com.hfm.jnidemo.JNIUtils.<clinit>(JNIUtils.java:9)
                                                                 at com.hfm.demo5.MainActivity.onCreate(MainActivity.java:16)
                                                                 at android.app.Activity.performCreate(Activity.java:6664)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by jreiser** [comment]
@pcheng74 Please run "readelf --headers /data/app/com.hfm.demo5-2/lib/arm64/libtest.so" then copy+paste the output here (or attach the output as a file; or attach the whole libtest.so file.)  I want to see the values that AndroidRuntime complains.  Thank you.

**Comment by jreiser** [comment]
Fixed by d979e19315d29ef70ea33e53c5e2725f0b638359 on 'devel' branch.

**Comment by pcheng74** [comment]
Hi jreiser,

I used --android-shlib command-line parameter, I still face the same issue.

Please see the following dump info from compressed so file by upx:


readelf --headers  libtest.so
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           AArch64
  Version:                           0x1
  Entry point address:               0x520
  Start of program headers:          64 (bytes into file)
  Start of section headers:          8200 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         7
  Size of section headers:           64 (bytes)
  Number of section headers:         3
  Section header string table index: 0

Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0] <no-name>         NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] <no-name>         STRTAB           0000000000000390  00000390
       00000000000000be  0000000000000000   A       0     0     1
  [ 2] <no-name>         DYNAMIC          0000000000021dc0  00000000cdceeb8d
       0000000000000210  0000000000000010  WA       1     0     8
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings)
  I (info), L (link order), G (group), T (TLS), E (exclude), x (unknown)
  O (extra OS processing required) o (OS specific), p (processor specific)

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000c2c 0x0000000000000c2c  R E    10000
  LOAD           0x0000000000001da8 0x0000000000021da8 0x0000000000021da8
                 0x0000000000000260 0x0000000000000260  RW     1000
  DYNAMIC        0x0000000000001dc0 0x0000000000021dc0 0x0000000000021dc0
                 0x0000000000000210 0x0000000000000210  RW     8
readelf: Error: no .dynamic section in the dynamic segment
  NOTE           0x00000000000001c8 0x00000000000001c8 0x00000000000001c8
                 0x0000000000000024 0x0000000000000024  R      4
  GNU_EH_FRAME   0x0000000000000f78 0x0000000000010f78 0x0000000000010f78
                 0x000000000000001c 0x000000000000001c  R      4
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     10
  GNU_RELRO      0x0000000000001da8 0x0000000000021da8 0x0000000000021da8
                 0x0000000000000258 0x0000000000000258  R      1
[libhuazict.zip](https://github.com/upx/upx/files/1041627/libhuazict.zip)

**Comment by jreiser** [comment]
@pcheng74 Thank you for libhuazict.zip.  https://github.com/upx/upx/commit/b7c91941b817b6f9647179f52696045e614f947a on 'devel' branch fixes .sh_offset.

**Comment by pcheng74** [comment]
Hi jreiser,

I used the latest code from devel branch, and however the same issue is still not fixed. and when I used readelf tool, it still return the same error: readelf: Error: no .dynamic section in the dynamic segment.

And if I run it from Android N device, the following log is captured:
06-01 08:17:08.249 14662-14662/com.hfm.demo5 A/libc: Fatal signal 5 (SIGTRAP), code 1 in tid 14662 (com.hfm.demo5)
                                                     
                                                     [ 06-01 08:17:08.269   816:  816 W/         ]
                                                     debuggerd: handling request: pid=14662 uid=10060 gid=10060 tid=14662

**Comment by pcheng74** [comment]
Hi jreiser,

Is there any update about this issue?

Thanks,

**Comment by jreiser** [comment]
@pcheng74 I believe that "readelf: Error: no .dynamic section in the dynamic segment" can be ignored.  While it is true that there is no Elf64_Shdr with name ".dynamic", nevertheless there is a ELF64_Shdr with .sh_type==SHT_DYNAMIC, and that is all that is checked by platform_bionic/linker/linker_phdr.cpp.  Also, the output from "readelf --dynamic libhuazict.so1" looks reasonable:
```
Dynamic section at offset 0x11dc0 contains 29 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
 0x000000000000000e (SONAME)             Library soname: [libhuazict.so]
  [[snip]]
```
The "Fatal signal 5 (SIGTRAP)" means that control has reached the upx de-compression stub for the compressed shared library.  So Android is acting like the compressed shared library is OK to execute.  I am debugging the upx de-compression stub now.

**Comment by pcheng74** [comment]
Is there any progress about this issue?

Thanks,
Peter

**Comment by jreiser** [comment]
@pcheng74 eef955a9dd941c826f1056f9320313297a32dc35 on 'devel' branch looks like it should work.

**Comment by kernelhack** [comment]
i found it modified b/bl instruction of original binary file, why ?

**Comment by kernelhack** [comment]
thanks for the answer, i encounter a bug in arm64-v8a which is loader decompress text data did not fix the b/bl instructions, so when i load the so file , it crashed.

**Comment by jreiser** [comment]
@kernelhack Please 'Attach' (upload) an example of the problem: a program or shared library that UPX does not process correctly.  Compress the example using gzip, or zip, etc. to save space.  Or, if still larger than a couple hundred KB, then please give a public URL so that I can download it directly.

**Comment by kernelhack** [comment]
[arm64-v8a.tar.gz](https://github.com/upx/upx/files/1247593/arm64-v8a.tar.gz)
thanks.

**Comment by kernelhack** [comment]
by the way, how i can disable this filter temporarily?

**Comment by jreiser** [comment]
upx --no-filter ...

**Comment by jreiser** [comment]
@kernelhack Please re-run upx on shared libs, then test.  Thank you.

**Comment by kernelhack** [comment]
@jreiser  still crashed, but error was changed to "Illegal instruction", here is the crashed shared library file.

[libdemo.so.tar.gz](https://github.com/upx/upx/files/1254906/libdemo.so.tar.gz)

**Comment by jreiser** [comment]
@kernelhack Which executable still crashed (upx, /usr/bin/ld, something using libdemo.so, ...), and what environment was it running in (the host OS and version, the target OS and version, the command line, the input fiiles, any relevant environment variables, ...)?  The upx runtime stub decompression works correctly for me in a bare stand-alone case:  "upx --android-shlib -o libdemo-upx.so libdemo.so", change the DT_NEEDED shlib names so that they can be symlinked to the right libraries in Fedora 25, change the .e_entry to point to the same place as the DT_INIT, run libdemo-upx.so as a main program under gdb, single-step the decompression.

https://bugzilla.redhat.com/show_bug.cgi?id=1486080 "SIGSEGV in LTO using /usr/bin/ld at simple_object_elf_find_sections() if 0==.e_shstrndx" shows a related bug in a gcc plugin for Link Time Optimization (LTO).

**Comment by kernelhack** [comment]
[libdemo.upx.so.tar.gz](https://github.com/upx/upx/files/1258899/libdemo.upx.so.tar.gz)
@jreiser  i use command line upx.out --android-shlib libdemo.so, then i load libdemo.so with dlopen , it crashed as "Illegal instruction".
my develop environment is ubuntu 17.04(4.10.0-32-generic #36-Ubuntu SMP Tue Aug 8 12:10:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux)
the attachment is upxed so file.
i will debug this with IDA pro.

devices info:
[ro.product.manufacturer]: [Xiaomi]
[ro.product.model]: [Redmi Note 4]
[ro.board.platform]: [mt6797]
[ro.build.version.release]: [6.0]
[ro.build.version.sdk]: [23]
[ro.build.version.security_patch]: [2017-02-05]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist]: [arm64-v8a,armeabi-v7a,armeabi]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: [arm64-v8a]
kernel:Linux version 3.18.22+ (builder@c3-miui-ota-bd05.bj) (gcc version 4.9.x-google 20140827 (prerelease) (GCC) ) #1 SMP PREEMPT Wed Mar 29 18:38:43 CST 2017

**Comment by joelihn** [comment]
@kernelhack have you resloved this problem?

> i use command line upx.out --android-shlib libdemo.so, then i load libdemo.so with dlopen , it crashed as "Illegal instruction".

**Comment by jreiser** [comment]
@kernelhack (and @joelihn) In <tt>libdemo.upx.so.tar.gz</tt> of Aug.28 it looks to me like <tt>libdemo.so</tt> has a bug in its list of initializers. 
```
$ sum libdemo.so
41254   118
$ ls -l libdemo.so
-rwxr-xr-x. 1 user group 120496 Oct 22 19:59 libdemo.so
$ readelf --all libdemo.so >libdemo.readelf

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000  # .text
                 0x0000000000002f80 0x0000000000002f80  R E    0x10000
  LOAD           0x0000000000003d90 0x0000000000013d90 0x0000000000013d90  # .data
                 0x0000000000019278 0x0000000000019278  RW     0x10000

$ grep INIT libdemo.readelf
  [14] .init_array       INIT_ARRAY       0000000000013d90  00003d90
 0x000000000000000c (INIT)               0x2c48
 0x0000000000000019 (INIT_ARRAY)         0x13d90  # at beginning of .data segment
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)  # one pointer
$ grep '13d9[08]' *.readelf  # all references to .init_array and .fini_array
  [14] .init_array       INIT_ARRAY       0000000000013d90  00003d90
  [15] .fini_array       FINI_ARRAY       0000000000013d98  00003d98
  LOAD           0x0000000000003d90 0x0000000000013d90 0x0000000000013d90
  GNU_RELRO      0x0000000000003d90 0x0000000000013d90 0x0000000000013d90
 0x0000000000000019 (INIT_ARRAY)         0x13d90  # but no relocation at that address!
 0x000000000000001a (FINI_ARRAY)         0x13d98
000000013d98  000000000403 R_AARCH64_RELATIV                    880  # reloc for a .fini function
$ od -Ax -tx4 libdemo.so -j 0x3d90 | sed 1q  # inspect beginning of .data in the file
003d90 00000000 00000000 00000000 00000000  # all zero
$ 
```
So the file contents of the INIT_ARRAY and FINI_ARRAY pointers (one each) is zero, and the FINI pointer has a RELATIV relocation which points to some function.  But the INIT pointer has no relocation.  So when the runtime loader calls the initializers, then we expect a SIGSEGV at pc==0.  This is what I observe using the program
```
#include <dlfcn.h>
#include <stdio.h>
#include <stdlib.h>

int
main(int argc, char *argv[])
{
    void *handle= dlopen("./libdemo.so", RTLD_LAZY);
    fprintf(stderr, "handle=%p\n", handle);
    if (!handle) {
        fprintf(stderr, "dlerror()=%s\n", dlerror());
    }
    return 0;
}
```
when run with <tt>export LD_LIBRARY_PATH=$PWD</tt>.  [I ran under Fedora 27 Linux on aarch64 after copying libc.so, libm.so, libdl.so, libstdc++.so from android-26 for arm64 to the current directory, so that the runtime loader would use the Android libraries.] When compressed using the <tt>devel</tt> branch, then I observe the same behavior: the de-compression has worked enough for the runtime loader to call the DT_INIT function, but when processing the DT_INIT_ARRAY list then calling the one (and only) item results in a SIGSEGV at pc==0 because there was no relocation of that pointer.  So the <tt>devel</tt> branch produces the same behavior for a compressed libdemo.so as for a never-compressed libdemo.so.

**Comment by jreiser** [comment]
I am closing this Issue because keeping it open seems not helpful to making progress.  Please open a new Issue if appropriate.
The last Comment by @pcheng74 relating to the original Description was answered on June 8.
@kernelhack introduced a second topic on Aug.23 [in the future please open a separate Issue instead] which was answered with a Commit on the same day.  On Oct.23 the last status relating to the second topic was diagnosis of bad ELF as input to UPX.  If the input is legitimate then it requires explanation.
