### ISSUE TITLE
UPX for armv7l platform ?

### ISSUE THREAD

**Issue by nmr50** [upx/upx#167]
## What's the problem (or question)?

Dear coders, could you - please - compile UPX for armv7l cpu now, and further ?
Many thanks in advance!:)

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`): (want to use) 3.94+
* Host Operating System and version: (wanted OS to use on) Debian GNU/Linux 7.11 (wheezy)
* Host CPU architecture: (wanted CPU to run UPX on) ARMv7 rev 0 (v7l)
* Target Operating System and version: Debian GNU/Linux 7.11 (wheezy)
* Target CPU architecture: ARMv7 rev 0 (v7l)

**Comment by jreiser** [comment]
The <tt>devel</tt> branch is built automatically on every <tt>git push</tt>, and one of the builds is for 32-bit ARM on Linux.  For instance: https://github.com/upx/upx-automatic-builds/commit/262c529307c721def7b76eee94b8369a80578dcc

**Comment by nmr50** [comment]
I still hope that this separated compiled stuff for armv7l will be inserted in the next UPX final build.
Thanks in advance!

**Comment by jreiser** [comment]
The request for the next release to contain a pre-built UPX for armv7l running on Linux has been noted.

Meanwhile, did you try the executable that is associated with the link above?  It's likely that the same recipe will be used when building the executables of the next release, so we'd like to know if the recipe does not work for you today.

**Comment by nmr50** [comment]
yes, it did not work:
[2018-02-03][21:08] /tmp>./262c529307c721def7b76eee94b8369a80578dcc 
./262c529307c721def7b76eee94b8369a80578dcc: 8: ./262c529307c721def7b76eee94b8369a80578dcc: Syntax error: newline unexpected

**Comment by jreiser** [comment]
OK, so improvement is necessary.  What Linux distribution and version was used for the failing run?

**Comment by nmr50** [comment]
[2018-02-03][21:08]/tmp>lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 7.11 (wheezy)
Release:        7.11
Codename:       wheezy
[2018-02-03][21:22]/tmp>uname -a
Linux R42 3.0.36+ #33 SMP PREEMPT Thu Sep 5 16:37:41 EEST 2013 armv7l GNU/Linux

**Comment by jreiser** [comment]
This is a mis-understanding of usage on GitHub.  The page https://github.com/upx/upx-automatic-builds/commit/262c529307c721def7b76eee94b8369a80578dcc is html which gives some context. Click on the View button to give a listing that has a Download button.  When you click the Download button then your browser offers a dialog to download a 1.8 MB file upx-git-95cedb664024.out.  Download it, and make it executable (<tt>chmod +x upx-git-95cedb664024.out</tt>).  That compiled-for-armv7l upx then works for me on
```
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
$ uname -a
Linux rpixub16042 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l armv7l armv7l GNU/Linux
```

**Comment by nmr50** [comment]
Did what you told me, and what I got in result:
-rw-r--r--  1 tmh  tmh   1838833 2018-02-03 23:54 upx-git-95cedb664024.out
[2018-02-03][23:54]/tmp>chmod +x upx-git-95cedb664024.out 
[2018-02-03][23:55]/tmp>./upx-git-95cedb664024.out 
./upx-git-95cedb664024.out: Command not found.
[2018-02-03][23:55]/tmp>ls -la upx-git-95cedb664024.out 
-rwxr-xr-x 1 tmh tmh 1838833 2018-02-03 23:54 upx-git-95cedb664024.out*

**Comment by jreiser** [comment]
<tt>Command not found</tt> is a complaint from the shell.  Which shell?  Does your environment restrict the $PATH in any way, such as with <tt>mount -noexec</tt>, or via some other means which distrusts executables that do not reside in /*bin, /usr/*bin, etc.?

More diagnosis using <tt>readelf</tt> from the <tt>binutils</tt> package, and <tt>strace</tt>:
```
$ readelf --segments upx*
  
Elf file type is EXEC (Executable file)
Entry point 0xa3bd
There are 10 program headers, starting at offset 52

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  EXIDX          0x17fcc4 0x00187cc4 0x00187cc4 0x02160 0x02160 R   0x4
  PHDR           0x000034 0x00008034 0x00008034 0x00140 0x00140 R E 0x4
  INTERP         0x000174 0x00008174 0x00008174 0x00013 0x00013 R   0x1
      [Requesting program interpreter: /lib/ld-linux.so.3]
  LOAD           0x000000 0x00008000 0x00008000 0x181e28 0x181e28 R E 0x8000
  LOAD           0x18288c 0x0019288c 0x0019288c 0x00b44 0x08184 RW  0x8000
  DYNAMIC        0x182f0c 0x00192f0c 0x00192f0c 0x000f0 0x000f0 RW  0x4
  NOTE           0x000188 0x00008188 0x00008188 0x00044 0x00044 R   0x4
  TLS            0x18288c 0x0019288c 0x0019288c 0x00000 0x0000c R   0x4
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW  0x4
  GNU_RELRO      0x18288c 0x0019288c 0x0019288c 0x00774 0x00774 R   0x1

 Section to Segment mapping:
  Segment Sections...
   00     .ARM.exidx
   01
   02     .interp
   03     .interp .note.ABI-tag .note.gnu.build-id .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rel.dyn .rel.plt .init .plt .text .fini .rodata .ARM.extab .ARM.exidx .eh_frame
   04     .init_array .fini_array .jcr .data.rel.ro .dynamic .got .data .bss
   05     .dynamic
   06     .note.ABI-tag .note.gnu.build-id
   07     .tbss
   08
   09     .init_array .fini_array .jcr .data.rel.ro .dynamic

$ strace ./upx* -f -o foo /bin/date
execve("./upx-git-95cedb664024.out", ["./upx-git-95cedb664024.out", "-f", "-o", "foo", "/bin/date"], [/* 65 vars */]) = 0
brk(NULL)                               = 0x12ec000
uname({sysname="Linux", nodename="rpixub16042", ...}) = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x76f7d000
access("/etc/ld.so.preload", R_OK)      = 0
open("/etc/ld.so.preload", O_RDONLY|O_CLOEXEC) = 3
fstat64(3, {st_mode=S_IFREG|0644, st_size=42, ...}) = 0
mmap2(NULL, 42, PROT_READ|PROT_WRITE, MAP_PRIVATE, 3, 0) = 0x76f7c000
close(3)                                = 0
open("/usr/lib/arm-linux-gnueabihf/libarmmem.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0h\5\0\0004\0\0\0"..., 512) = 512
lseek(3, 17960, SEEK_SET)               = 17960
read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 960) = 960
lseek(3, 17696, SEEK_SET)               = 17696
read(3, "A.\0\0\0aeabi\0\1$\0\0\0\0056\0\6\6\10\1\t\1\n\3\f\1\22\4\24"..., 47) = 47
fstat64(3, {st_mode=S_IFREG|0644, st_size=18920, ...}) = 0
mmap2(NULL, 83236, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x76f42000
mprotect(0x76f47000, 61440, PROT_NONE)  = 0
mmap2(0x76f56000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x4000) = 0x76f56000
mprotect(0x7e924000, 4096, PROT_READ|PROT_WRITE|PROT_EXEC|PROT_GROWSDOWN) = 0
close(3)                                = 0
munmap(0x76f7c000, 42)                  = 0
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat64(3, {st_mode=S_IFREG|0644, st_size=80803, ...}) = 0
mmap2(NULL, 80803, PROT_READ, MAP_PRIVATE, 3, 0) = 0x76f2e000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/arm-linux-gnueabihf/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\1\1\1\3\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\331i\1\0004\0\0\0"..., 512) = 512
lseek(3, 894128, SEEK_SET)              = 894128
read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 2960) = 2960
lseek(3, 888324, SEEK_SET)              = 888324
read(3, "A2\0\0\0aeabi\0\1(\0\0\0\0057-A\0\6\n\7A\10\1\t\2\n\3\f"..., 51) = 51
fstat64(3, {st_mode=S_IFREG|0755, st_size=897088, ...}) = 0
mmap2(NULL, 963928, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x76e42000
mprotect(0x76f18000, 65536, PROT_NONE)  = 0
mmap2(0x76f28000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xd6000) = 0x76f28000
mmap2(0x76f2b000, 9560, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x76f2b000
close(3)                                = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x76f7c000
set_tls(0x76f7c4c0, 0x76f7cba8, 0x76f7f050, 0x76f7c4c0, 0x76f7f050) = 0
mprotect(0x76f28000, 8192, PROT_READ)   = 0
mprotect(0x76f42000, 20480, PROT_READ|PROT_WRITE) = 0
mprotect(0x76f42000, 20480, PROT_READ|PROT_EXEC) = 0
cacheflush(0x76f42000, 0x76f47000, 0, 0x7e923e98, 0xf0002) = 0
mprotect(0x192000, 4096, PROT_READ)     = 0
mprotect(0x76f7e000, 4096, PROT_READ)   = 0
munmap(0x76f2e000, 80803)               = 0
   [[snip]]  # many more lines, but the above shows that upx de-compression did work

**Comment by nmr50** [comment]
tcsh I use, here is the sample I run ls from current folder and then run upx* from the same folder:
[2018-02-04][0:24]~/bin/comp>./ls 
inxi.zip  ls  sirc-2.211  upx-git-95cedb664024.out
[2018-02-04][0:24]~/bin/comp>./upx-git-95cedb664024.out 
./upx-git-95cedb664024.out: Command not found.

About readelf:
[2018-02-04][0:30]~/bin/comp>readelf --segments ./upx*

Elf file type is EXEC (Executable file)
Entry point 0xa3bd
There are 10 program headers, starting at offset 52

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  EXIDX          0x17fcc4 0x00187cc4 0x00187cc4 0x02160 0x02160 R   0x4
  PHDR           0x000034 0x00008034 0x00008034 0x00140 0x00140 R E 0x4
  INTERP         0x000174 0x00008174 0x00008174 0x00013 0x00013 R   0x1
      [Requesting program interpreter: /lib/ld-linux.so.3]
  LOAD           0x000000 0x00008000 0x00008000 0x181e28 0x181e28 R E 0x8000
  LOAD           0x18288c 0x0019288c 0x0019288c 0x00b44 0x08184 RW  0x8000
  DYNAMIC        0x182f0c 0x00192f0c 0x00192f0c 0x000f0 0x000f0 RW  0x4
  NOTE           0x000188 0x00008188 0x00008188 0x00044 0x00044 R   0x4
  TLS            0x18288c 0x0019288c 0x0019288c 0x00000 0x0000c R   0x4
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW  0x4
  GNU_RELRO      0x18288c 0x0019288c 0x0019288c 0x00774 0x00774 R   0x1

 Section to Segment mapping:
  Segment Sections...
   00     .ARM.exidx 
   01     
   02     .interp 
   03     .interp .note.ABI-tag .note.gnu.build-id .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rel.dyn .rel.plt .init .plt .text .fini .rodata .ARM.extab .ARM.exidx .eh_frame 
   04     .init_array .fini_array .jcr .data.rel.ro .dynamic .got .data .bss 
   05     .dynamic 
   06     .note.ABI-tag .note.gnu.build-id 
   07     .tbss 
   08     
   09     .init_array .fini_array .jcr .data.rel.ro .dynamic 

About strace:
[2018-02-04][0:31]~/bin/comp>strace ./upx* -f -o foo /bin/date
execve("./upx-git-95cedb664024.out", ["./upx-git-95cedb664024.out", "-f", "-o", "foo", "/bin/date"], [/* 33 vars */]) = -1 ENOENT (No such file or directory)
dup(2)                                  = 3
fcntl64(3, F_GETFL)                     = 0x20002 (flags O_RDWR|O_LARGEFILE)
fstat64(3, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 6), ...}) = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x4002c000
_llseek(3, 0, 0xbee42250, SEEK_CUR)     = -1 ESPIPE (Illegal seek)
write(3, "strace: exec: No such file or di"..., 40strace: exec: No such file or directory
) = 40
close(3)                                = 0
munmap(0x4002c000, 4096)                = 0
exit_group(1)                           = ?

**Comment by jreiser** [comment]
Your "uname -a" reports
```
Linux R42 3.0.36+ #33 SMP PREEMPT Thu Sep 5 16:37:41 EEST 2013 armv7l GNU/Linux
```
which is almost 4.5 years old (Sep 2013 to Feb 2018) and might be part of the problem.  What does
```
$ readelf --segments /bin/ls
```
say for the usual <tt>ls</tt> command?

**Comment by nmr50** [comment]
I understand that this mediaplayer wasn't made to run "normal" linux at all, but I am compiling all the program w/o problems on it...
About system /bin/ls: 
[2018-02-04][0:39]~/bin/comp>readelf --segments /bin/ls

Elf file type is EXEC (Executable file)
Entry point 0xba0d
There are 9 program headers, starting at offset 52

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  EXIDX          0x011274 0x00019274 0x00019274 0x00028 0x00028 R   0x4
  PHDR           0x000034 0x00008034 0x00008034 0x00120 0x00120 R E 0x4
  INTERP         0x000154 0x00008154 0x00008154 0x00019 0x00019 R   0x1
      [Requesting program interpreter: /lib/ld-linux-armhf.so.3]
  LOAD           0x000000 0x00008000 0x00008000 0x112a0 0x112a0 R E 0x8000
  LOAD           0x011edc 0x00021edc 0x00021edc 0x003f8 0x0108c RW  0x8000
  DYNAMIC        0x011ee8 0x00021ee8 0x00021ee8 0x00118 0x00118 RW  0x4
  NOTE           0x000170 0x00008170 0x00008170 0x00044 0x00044 R   0x4
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW  0x4
  GNU_RELRO      0x011edc 0x00021edc 0x00021edc 0x00124 0x00124 R   0x1

 Section to Segment mapping:
  Segment Sections...
   00     .ARM.exidx 
   01     
   02     .interp 
   03     .interp .note.ABI-tag .note.gnu.build-id .hash .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rel.dyn .rel.plt .init .plt .text .fini .rodata .ARM.exidx .eh_frame 
   04     .init_array .fini_array .jcr .dynamic .got .data .bss 
   05     .dynamic 
   06     .note.ABI-tag .note.gnu.build-id 
   07     
   08     .init_array .fini_array .jcr .dynamic 

About mine compiled version in my ~:
[2018-02-04][0:41]~/bin/comp>readelf --segments ~/bin/ls

Elf file type is EXEC (Executable file)
Entry point 0xa3a9
There are 8 program headers, starting at offset 52

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  EXIDX          0x01e444 0x00026444 0x00026444 0x00028 0x00028 R   0x4
  PHDR           0x000034 0x00008034 0x00008034 0x00100 0x00100 R E 0x4
  INTERP         0x000134 0x00008134 0x00008134 0x00019 0x00019 R   0x1
      [Requesting program interpreter: /lib/ld-linux-armhf.so.3]
  LOAD           0x000000 0x00008000 0x00008000 0x1e470 0x1e470 R E 0x8000
  LOAD           0x01e470 0x0002e470 0x0002e470 0x00470 0x01690 RW  0x8000
  DYNAMIC        0x01e47c 0x0002e47c 0x0002e47c 0x00100 0x00100 RW  0x4
  NOTE           0x000150 0x00008150 0x00008150 0x00044 0x00044 R   0x4
  GNU_STACK      0x000000 0x00000000 0x00000000 0x00000 0x00000 RW  0x4

 Section to Segment mapping:
  Segment Sections...
   00     .ARM.exidx 
   01     
   02     .interp 
   03     .interp .note.ABI-tag .note.gnu.build-id .hash .gnu.hash .dynsym .dynstr .gnu.version .gnu.version_r .rel.dyn .rel.plt .init .plt .text .fini .rodata .ARM.exidx .eh_frame 
   04     .init_array .fini_array .jcr .dynamic .got .data .bss 
   05     .dynamic 
   06     .note.ABI-tag .note.gnu.build-id 
   07

**Comment by jreiser** [comment]
upx wants
```
[Requesting program interpreter: /lib/ld-linux.so.3]
```
but /bin/ls wants
```
[Requesting program interpreter: /lib/ld-linux-armhf.so.3]
```
This is a difference between Debian-based Linux distributions and Fedora-based Linux distributions, and is one of the problems with distributing binary executables for Linux.

So if the machine does not have <tt>/lib/ld-linux.so.3</tt> then make a symlink so that the upx request for /lib/ld-linux.so.3 gets forwarded to the actual file /lib/ld-linux-armhf.so.3; such as:
```
# ln -s /lib/ld-linux-armhf.so.3 /lib/ld-linux.so.3
# ls -l /lib/ld-linux.so.3
lrwxrwxrwx.  1 user group  24 Feb  3  hh:mm /lib/ld-linux.so.3 ->  /lib/ld-linux-armhf.so.3
```

**Comment by nmr50** [comment]
heh, something changed:
[2018-02-04][1:02]/lib#ln -s /lib/arm-linux-gnueabihf/ld-2.13.so /lib/ld-linux.so.3 
[2018-02-04][1:02]/lib#l ld-linux.so.3 
lrwxrwxrwx 1 root root 35 2018-02-04 01:02 ld-linux.so.3 -> /lib/arm-linux-gnueabihf/ld-2.13.so*
[2018-02-04][1:02]/lib#exit
[2018-02-04][1:02]~/bin/comp>./upx-git-95cedb664024.out 
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2017
UPX git-95cedb  Markus Oberhumer, Laszlo Molnar & John Reiser   May 13th 2017

Should I wait for fresh release now ?:)

**Comment by jreiser** [comment]
Should be working now.  Find the new pre-compiled binary by analogy with the link for the previous one and the link for "0ef00e9"  on the "Fix --lzma" line above.  (The auto-build system might take half an hour or so.)

**Comment by nmr50** [comment]
Still getting old build, I'll try to test fresh building later and then report about results. Thanks !

**Comment by tamalsaha** [comment]
Any plans to support arm64 ? We are using ARM 64 bit servers available on Packet. We use upx to trim down our Go binaries.

cc: @vielmetti

**Comment by tamalsaha** [comment]
I am building on Ubuntu 16.04 LTS using upx 3.94 . Here is my arm64 binary https://github.com/kubepack/onessl/releases/download/0.1.0/onessl-linux-arm64

**Comment by jreiser** [comment]
@tamalsaha Please try the <tt>devel</tt> branch.  Both --lzma and the default compression algorithm work for me, when I run the compressed onessl-linux-arm64.

**Comment by jreiser** [comment]
upx-3.95 (released 6 months ago: August 2018) should work.  If not, please re-open (or submit a new Issue) and Attach a specific failing case, along with detailed information on the Linux that is being used ((`uname -a` etc.)  Closing this issued.
